version: "3"
services:
  web:
    image: ricardotulio/hello-express
    environment:
      - PUBLIC_URL=/web
    ports:
      - "3006:3000"
    networks:
      - letsencrypt-docker-compose
    restart: unless-stopped
  auth:
    image: yassinedockeer/z4c-auth-api:latest
    environment:
      - PUBLIC_URL=/auth
    ports:
      - "3001:3000"
    networks:
      - letsencrypt-docker-compose
    restart: unless-stopped
  doc:
    image: yassinedockeer/z4c-doc-api:latest
    environment:
      - PUBLIC_URL=/doc
    ports:
      - "3002:3000"
    networks:
      - letsencrypt-docker-compose
    restart: unless-stopped
  gateway:
    build:
      context: ./gateway
    ports:
      - "3000:80"
    networks:
      - letsencrypt-docker-compose
    restart: unless-stopped
    depends_on:
      - doc
      - web
      - auth
networks:
  letsencrypt-docker-compose:
    external:
      name: letsencrypt-docker-compose_default
